### PR TITLE
Update base image names with namespace

### PR DESCRIPTION
**Pull request by kyguy**

### CODE REVIEW

**Comment by kyguy** [comment]
Yes, tested with an OSBS scratch build, and the replacement logic doesn't disturb the build. It appears we are leading the charge with the image name change, others must be swapping the image name when doing local builds, using a tag other than "7-released", or relying on scratch builds for development.

**Comment by ppatierno** [comment]
ok sounds good! just double check with @lulf on how they do AMQ online images local build. Do you change the image descriptor file with `rh-osbs` prefix or not?

**Comment by kyguy** [comment]
Although it wouldn't be difficult to create a Makefile to do this swap, I think it would be overkill. The image name in the internal registry changed from `ubi-minimal` to `rh-osbs/ubi-minimal`. OSBS does do a base image name swap at build time to account for the image name change probably so it doesn't disturb users that are still using the old image name, `ubi7-minimal`, but it still respects users who have adapted to the new image name, `rh-osbs/ubi7-minimal`. That being said, feel free to close the this and create an issue if you feel strongly about it, it doesn't really matter to me either way

**Comment by ppatierno** [comment]
I see your point. I was just wondering why the others didn't change that. Maybe just because they don't do any local builds?

**Comment by kyguy** [comment]
Yea, I think you are right, I think the other teams are relying primarily on CPaaS for their builds

**Pull request merged**
