### PR TITLE
Updating install/example files for 1.2.0 release

### PR DESCRIPTION
**Pull request by kyguy**
Minor changes from the released 1.2.0 install files

### CODE REVIEW

**Comment by scholzj** [comment]
Why are we changing this?

**Comment by kyguy** [comment]
To match the official install/release files so we can tag make these files available from this repo. Do the changes look incorrect?

**Comment by scholzj** [comment]
Well, TBH I think the installation files should have used v1. Although in general both should work.

**Comment by kyguy** [comment]
As discussed with Jakub, since v1 is the correct apiVersion we will drop this change and stick with v1

**Pull request closed without merging**
