### PR TITLE
Added OLM manifests related files

### PR DESCRIPTION
**Pull request by ppatierno**

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
I guess its ok. Were there really no changes to RBAC since 0.22?

**Review by kyguy — APPROVED** [review]
Looks great!

**Comment by ppatierno** [comment]
@scholzj I just copied and pasted the CRDs and RBACs from the upstream community OLM files and then fixing things around. So answering your question, the RBAC are coming directly from 0.24.0 upstream so no changes since 0.22.0 then :)

**Comment by ppatierno** [comment]
@scholzj I just copied and pasted the CRDs and RBACs from the upstream community OLM files and then fixing things around. So answering your question, the RBAC are coming directly from 0.24.0 upstream so no changes since 0.22.0 then :)

**Pull request merged**
