### PR TITLE
Update MD5 + modules for AMQ Streams 2.2.1 CR

### PR DESCRIPTION
**Pull request by kyguy**

### CODE REVIEW

**Comment by kyguy** [comment]
Hey @OwenCorrigan76 could you verify these MD5 checksums?

**Comment by ppatierno** [comment]
@kyguy @OwenCorrigan76 hold on on merging this PR. Some discussion around the Quarkus version used in the drain cleaner is going on.

**Comment by ppatierno** [comment]
We addressed the discussion offline, no new drain cleaner build needed, MD5s are good to me!

**Review by ppatierno — APPROVED** [review]

**Comment by OwenCorrigan76** [comment]
MD5s match and look good to me.

**Review by OwenCorrigan76 — APPROVED** [review]

**Pull request merged**
