### PR TITLE
Switch to internal registry names in CSV

### PR DESCRIPTION
**Pull request by kyguy**
OSBS digest pinning automation appears to only work when internal registry names are used within our CSV file. 

With the interest of time, let's use the internal registry pull specs until we sort out the issue with OSBS

### CODE REVIEW

**Review by MikeEdgar — COMMENTED** [review]
Looks good. Are there also changes to the Python scripts?

**Review by k-wall — APPROVED** [review]
seems reasonable to me

**Comment by kyguy** [comment]
> Looks good. Are there also changes to the Python scripts?

Argh yes, I missed that, let me update it

**Comment by kyguy** [comment]
>  Looks good. Are there also changes to the Python scripts?

@MikeEdgar Just tested and the Python scripts will work fine with the internal pull specs. No changes needed. I have added an example and added a test to show it works.

**Review by MikeEdgar — APPROVED** [review]

**Comment by kyguy** [comment]
> Just tested, the Python scripts work fine with the internal pull specs as they are. No changes needed. Regardless, I have added an example and test just to be safe.

Upon further testing (from internal `render_templates` script as suggested by @MikeEdgar ) it looks like the Python scripts required more changes to accommodate internal registry names, I also found some other bugs along the way. 

The required changes and bug fixes should be covered in the latest commit. I have also added some more tests for more coverage to avoid these bugs in the future

**Review by MikeEdgar — APPROVED** [review]
:+1:

**Review by k-wall — APPROVED** [review]

**Review by OwenCorrigan76 — APPROVED** [review]

**Pull request merged**
